task_manager:
  ros__parameters:
    autostart: true
    autostart_delay_sec: 4.0
    launch_targets:
      - "description:robot_bringup:description.launch.py"
      - "web:robot_bringup:web.launch.py"
      - "hardware:robot_bringup:hardware.launch.py"
      - "lidar:robot_bringup:lidar.launch.py"
      - "hardware_supervisor:robot_bringup:hardware_supervisor.launch.py"
      - "esp_drive_agent:robot_bringup:esp_drive_agent.launch.py"
      - "esp_gripper_agent:robot_bringup:esp_gripper_agent.launch.py"
      - "vision:robot_bringup:vision.launch.py"
      - "camera:camera:camera.launch.py"
      - "corner_manager:corner_manager:corner_manager.launch.py"
      - "object_manager:object_manager:object_manager.launch.py"
      - "object_task_executor:object_task_executor:object_task_executor.launch.py"
      - "room_vision:room_vision:room_vision.launch.py"
      - "object_localizer:object_localizer:object_localizer.launch.py"
      - "edge_color:edge_color:edge_color.launch.py"
      - "odometry:robot_bringup:odometry.launch.py"
      - "imu:imu:imu.launch.py"
      - "magnetometer:mmc5603:mmc5603.launch.py"
      - "imu_filter:imu_mag_fusion:madgwick.launch.py"
      - "imu_covariance_fixer:imu_mag_fusion:imu_covariance_fixer.launch.py"
      - "imu_fusion:imu_mag_fusion:madgwick_with_cov_fix.launch.py"
      - "ekf:ekf:ekf.launch.py"
      - "mapping:robot_bringup:mapping.launch.py"
      - "slam:mapping:mapping.launch.py"
      - "frontier_explorer:frontier_explorer:frontier_explorer.launch.py"
      - "navigation:navigation:navigation.launch.py"
      - "navigation_slam:navigation:navigation_slam.launch.py"
      - "navigation_debug:navigation:navigation_debug.launch.py"
      - "map_saver:mapping:map_saver.launch.py"
    start_all_targets:
      - "web"
      - "mapping"
