services:
  ros2-dev:
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: ros2_jazzy_dev
    working_dir: /ros2_ws
    stdin_open: true
    tty: true
    volumes:
      - ./ros2_ws:/ros2_ws
      - ./simulation:/simulation
      - ./firmware:/firmware
    environment:
      - ROS_DOMAIN_ID=0
    command: bash