color_edge_detection_node:
  ros__parameters:
    
    image_topic: /camera/image_raw
    camera_info_topic: /camera/camera_info

    
    debug_view: false
    publish_debug_image: true

    # Mindestgröße für erkannte Flächen (Pixel)
    min_contour_area: 800.0

    saturation_min: 80
    value_min: 60


color_wall_projector_node:
  ros__parameters:
    input_topic: /color_patches/detected
    output_topic: /color_patches/projected
    camera_info_topic: /camera/camera_info
    image_topic: /camera/image_raw
    publish_debug_image: true

    camera_frame: camera_optical_link
    map_frame: map

    arena_x_min: -1.5
    arena_x_max: 1.5
    arena_y_min: -1.0
    arena_y_max: 1.0

    wall_z_min: 0.05
    wall_z_max: 1.20

    min_projection_distance: 0.1
    max_projection_distance: 5.0

color_corner_validator_node:
  ros__parameters:
    input_topic: /color_patches/projected
    output_topic: /color_corners/valid
    json_output_topic: /color_corners/valid_json
    marker_topic: /color_corners/markers
    image_topic: /camera/image_raw
    detected_topic: /color_patches/detected
    publish_debug_image: true

    map_frame: map

    arena_x_min: -1.5
    arena_x_max: 1.5
    arena_y_min: -1.0
    arena_y_max: 1.0

    wall_distance_tolerance: 0.08
    corner_distance_tolerance: 0.35

    # A3 hochkant: 297 mm x 420 mm
    a3_width: 0.297
    a3_height: 0.420
    a3_size_tolerance: 0.35

    # Keine fixen Farben, aber kein weiß/grau/schwarz
    min_s_for_color: 40.0
    min_v_for_color: 50.0

    publish_json: true
    publish_markers: true