mpu6050_node:
  ros__parameters:
    # I2C 
    i2c_bus: "/dev/i2c-1"
    device_address: 0x68
    # Sensor configuration
    accel_scale: 16384.0
    gyro_scale: 131.0
    # Frame
    frame_id: "imu_link"
    # Update rate
    publish_rate: 100
    # Noise covariance
    angular_velocity_covariance: [0.01, 0.0, 0.0,
                                  0.0, 0.01, 0.0,
                                  0.0, 0.0, 0.01]

    linear_acceleration_covariance: [0.04, 0.0, 0.0,
                                     0.0, 0.04, 0.0,
                                     0.0, 0.0, 0.04]

    orientation_covariance: [-1.0, 0.0, 0.0,
                             0.0, 0.0, 0.0,
                             0.0, 0.0, 0.0]

    # Offset
    accel_offset_x: 0.0
    accel_offset_y: 0.0
    accel_offset_z: 0.0

    gyro_offset_x: 0.0
    gyro_offset_y: 0.0
    gyro_offset_z: 0.0