mpu6050_node:
  ros__parameters:
    # I2C
    i2c_bus: "/dev/i2c-1"
    i2c_address: 104
    # Sensor configuration
    accel_scale: 16384.0
    gyro_scale: 131.0
    # Frame
    frame_id: "imu_link"
    # Update rate
    update_rate: 5.0
    # Noise covariance
    angular_velocity_covariance: [0.01, 0.0, 0.0,
                                  0.0, 0.01, 0.0,
                                  0.0, 0.0, 0.01]

    linear_acceleration_covariance: [0.04, 0.0, 0.0,
                                     0.0, 0.04, 0.0,
                                     0.0, 0.0, 0.04]

    orientation_covariance: [-1.0, 0.0, 0.0,
                             0.0, 0.0, 0.0,
                             0.0, 0.0, 0.0]

    # Kalibrierungsoffsets (von run_startup_calibration berechnet und hier eintragen)
    accel_offset_x: 0.0
    accel_offset_y: 0.0
    accel_offset_z: 0.0

    gyro_offset_x: 0.0
    gyro_offset_y: 0.0
    gyro_offset_z: 0.0

    # Startup-Kalibrierung: true = beim Start N Samples mitteln und Offsets setzen
    # Roboter muss dabei vollkommen stillstehen!
    calibrate_on_start: false
    calibration_samples: 200
